// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpApiSearch")>]
[<assembly: AssemblyProductAttribute("FSharpApiSearch")>]
[<assembly: AssemblyDescriptionAttribute("F# API search engine")>]
[<assembly: AssemblyVersionAttribute("3.0.4")>]
[<assembly: AssemblyFileVersionAttribute("3.0.4")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpApiSearch"
    let [<Literal>] AssemblyProduct = "FSharpApiSearch"
    let [<Literal>] AssemblyDescription = "F# API search engine"
    let [<Literal>] AssemblyVersion = "3.0.4"
    let [<Literal>] AssemblyFileVersion = "3.0.4"
    let [<Literal>] AssemblyConfiguration = "Release"
