// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpApiSearch.Database")>]
[<assembly: AssemblyProductAttribute("FSharpApiSearch")>]
[<assembly: AssemblyDescriptionAttribute("F# API search engine")>]
[<assembly: AssemblyVersionAttribute("4.0.0")>]
[<assembly: AssemblyFileVersionAttribute("4.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpApiSearch.Database"
    let [<Literal>] AssemblyProduct = "FSharpApiSearch"
    let [<Literal>] AssemblyDescription = "F# API search engine"
    let [<Literal>] AssemblyVersion = "4.0.0"
    let [<Literal>] AssemblyFileVersion = "4.0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
